version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Educa
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lerton
      - POSTGRES_PASSWORD=lerton123
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
    