version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Educa
    ports:
      - 8000:8000
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-g0*+z+7upnfmls7wfji$(+ekehx76*+aydekg-9$#5qmx7aemx"
      - "DJANGO_DEBUG=True"
      - "DJANGO_DB_ENGINE=django.db.backends.postgresql"
      - "DJANGO_DB_NAME=postgres"
      - "DJANGO_DB_USER=lerton"
      - "DJANGO_DB_HOST=db"
      - "DJANGO_DB_PASSWORD=lerton123"
      - "DJANGO_DB_PORT=5432"
      - "DJANGO_EMAIL_HOST=smtp.gmail.com"
      - "DJANGO_EMAIL_HOST_USER=lertonjosine@gmail.com"
      - "DJANGO_EMAIL_HOST_PASSWORD=qdqpmuylsdzvhtnx"
      - "DJANGO_EMAIL_USE_TLS=True"
      - "DJANGO_EMAIL_PORT=587"
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lerton
      - POSTGRES_PASSWORD=lerton123
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
    name: postgres_data
    