version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Educa
    ports:
      - 8000:8000
    environment:
      - "DJANGO_SECRET_KEY=vUv9IpcLXgllVlUKDhv7P2Q2e9JSDAo0j8rktKF9Bs_1eXxh76E"
      - "DJANGO_DEBUG=False"
      - "DJANGO_DB_ENGINE=django.db.backends.postgresql"
      - "DJANGO_DB_NAME=postgres"
      - "DJANGO_DB_USER=lerton"
      - "DJANGO_DB_HOST=db"
      - "DJANGO_DB_PASSWORD=lerton123"
      - "DJANGO_DB_PORT=5432"
      - "DJANGO_SECURE_SSL_REDIRECT=True"
      - "DJANGO_SECURE_HSTS_SECONDS=2592000"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=True"
      - "DJANGO_SECURE_HSTS_PRELOAD=True"
      - "DJANGO_CSRF_COOKIE_SECURE=True"
      - "DJANGO_SESSION_COOKIE_SECURE=True"
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lerton
      - POSTGRES_PASSWORD=lerton123
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
    name: postgres_data
    