# Generated by Django 5.1.1 on 2024-10-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cover',
            field=models.ImageField(default='course-1.jpg', upload_to='media/'),
        ),
    ]
