# Generated by Django 5.1.1 on 2024-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cover',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
